name: CI PR

on:
  pull_request:
    branches:
      - main

jobs:
  build-main:
    steps:
      - name: dummy
        run: true
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: List files
      run: true
