name: Retry Dequeued Merge

on:
  pull_request:
    types: ['dequeued']  # Custom event for dequeuing from the merge queue

jobs:
  retry_queue:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    if: ${{ github.event.reason != 'MANUAL' }}

    steps:
      - name: Checkout the code
        uses: actions/checkout@v4

      - name: Retry merge queue
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PR_NUMBER: ${{ github.event.pull_request.number }}
          REASON: ${{ github.event.reason }}
        run: |
          echo "Attempting to merge $PR_NUMBER $REASON"
          gh pr merge --auto "$PR_NUMBER"
