name: Retry Dequeued Merge

on:
  pull_request:
    types: ['dequeued']  # Custom event for dequeuing from the merge queue

jobs:
  retry_queue:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write

    # Skip job if a human removed this from the queue
    if: ${{ github.event.reason != 'MANUAL' }}

    steps:
      - name: Checkout the code
        uses: actions/checkout@v4

      # TODO
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: |
          echo "$GITHUB_CONTEXT"

      - name: Retry merge queue
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PR_NUMBER: ${{ github.event.pull_request.number }}
          REASON: ${{ github.event.reason }}
        run: |
          retries=$(gh pr view --json labels --jq '.labels[].name' "$PR_NUMBER" | grep 'retry-') || true
          attempt=0
          case "$retries" in
          *retry-2*)
              # Retry limit reached, delete labels and exit
              gh pr edit --remove-label retry-0 --remove-label retry-1 --remove-label retry-2 "$PR_NUMBER"
              exit 0
              ;;
          *retry-1*)
              attempt=2
              ;;
          *retry-0*)
              attempt=1
              ;;
          esac

          echo "Attempting to merge $PR_NUMBER $REASON"
          gh pr merge --auto "$PR_NUMBER" &&
              gh pr edit --add-label "retry-$attempt" "$PR_NUMBER"
